### ISSUE TITLE
Latest release is 4.0.0 from February

### ISSUE THREAD

**Issue by alex-weej** [ReactiveX/RxCpp#406]
(First of all, thanks to all who contribute to this awesome library!)

Not sure if I'm missing something but the latest release is 4.0.0 which is quite old. Is it expected that people use `master` in general? Or is it common to use the latest release?

Thanks

**Comment by kirkshoop** [comment]
I use master ;)

I tend to release when master has really diverged or has taken breaking changes. I am open to changes in the release process.

Thanks!
