### ISSUE TITLE
buffer() - Static assert during compilation when passing named constant as count

### ISSUE THREAD

**Issue by pvaibhav** [ReactiveX/RxCpp#410]
# Problem

Calling `buffer(count)` on an observable, where `count` is a constant of type `static constexpr uint16_t` fails to compile with the following assert:

```
Static_assert failed "buffer takes (Count, optional Skip)"
```

from file Rx/v2/src/rxcpp/operators/rx-buffer_count.hpp line 172.

- Hard-coding a numerical value works.
- Changing from `constexpr` to just `const` doesn't help.
- Other combinations of `static`, `auto` etc. also don't help. Only a hardcoded number works.

# How to reproduce

I wanted to convert a byte vector into a stream of 50 packets of 20 bytes each, skipping some bytes from the start:

```
  auto packets =
      observable<>::iterate(binFile)
      | skip(start)
      | buffer(kPacketSize)
      | take(kPacketBlock);
```

where `binFile` is a `std::vector<uint8_t>`, `kPacketSize` is `static constexpr uint16_t kPacketSize = 20;` and `kPacketBlock` is similarly 50.

This fails to compile at the `buffer()` line. The `take()` has no problem.

# Workaround

Replacing `buffer(kPacketSize)` with `buffer(20)` works.

Any ideas why? Is this by design? Why would even `constexpr` values not work? Thanks.

**Comment by kirkshoop** [comment]
I am as confused as you are. This code was written for C++11, but I would not expect this to fail with constexpr.

another workaround should be `| buffer(static_cast<int>(kPacketSize))`

I looked at the code and the odd bit is that the args to each algorithm are passed to make_tuple(), if the std lib tuple has a problem storing constexpr, that might be the isssue..
