### ISSUE TITLE
error in buffer_with_time_or_count

### ISSUE THREAD

**Issue by nguoithichkhampha** [ReactiveX/RxCpp#415]
Hi team,
I got many crashs in function buffer_with_time_or_count. this is the crash stack trace
Crash reason:  EXC_SOFTWARE / SIGABRT
Crash address: 0x7fff5a6bbfce
Process uptime: 61 seconds

Thread 31 (crashed)
 0  libsystem_kernel.dylib + 0x1bfce
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x0000700004ea3be8   rbx = 0x0000700004ea5000
    rsi = 0x0000000000000006   rdi = 0x000000000000a607
    rbp = 0x0000700004ea3c20   rsp = 0x0000700004ea3be8
     r8 = 0x0000000000000010    r9 = 0x00000000fffffff0
    r10 = 0x0000000000000000   r11 = 0x0000000000000206
    r12 = 0x000000000000a607   r13 = 0x000000010e72b000
    r14 = 0x0000000000000006   r15 = 0x000000000000002d
    rip = 0x00007fff5a6bbfce
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x5d30a
    rbp = 0x0000700004ea3c50   rsp = 0x0000700004ea3c30
    rip = 0x00007fff5a61830a
    Found by: previous frame's frame pointer
 2  libsystem_malloc.dylib + 0xeb28
    rbp = 0x0000700004ea3d70   rsp = 0x0000700004ea3c60
    rip = 0x00007fff5a720b28
    Found by: previous frame's frame pointer
 3  libsystem_malloc.dylib + 0x3658
    rbp = 0x0000700004ea3db0   rsp = 0x0000700004ea3d80
    rip = 0x00007fff5a715658
    Found by: previous frame's frame pointer
 4  libsystem_malloc.dylib + 0x2403
    rbp = 0x0000700004ea3e80   rsp = 0x0000700004ea3dc0
    rip = 0x00007fff5a714403
    Found by: previous frame's frame pointer
 5  libsystem_malloc.dylib + 0x2201
    rbp = 0x0000700004ea3eb0   rsp = 0x0000700004ea3e90
    rip = 0x00007fff5a714201
    Found by: previous frame's frame pointer
 6  libsystem_malloc.dylib + 0x150b
    rbp = 0x0000700004ea3ed0   rsp = 0x0000700004ea3ec0
    rip = 0x00007fff5a71350b
    Found by: previous frame's frame pointer
 7  libc++abi.dylib + 0x1628
    rbp = 0x0000700004ea3ef0   rsp = 0x0000700004ea3ee0
    rip = 0x00007fff585fa628
    Found by: previous frame's frame pointer
 8  CortexService!__ZNSt3__16vectorINS_5arrayIfLm8EEENS_9allocatorIS2_EEE8allocateEm + 0x198
    rbp = 0x0000700004ea40a0   rsp = 0x0000700004ea3f00
    rip = 0x000000010793ffd8
    Found by: previous frame's frame pointer
 9  CortexService!__ZNSt3__16vectorINS_5arrayIfLm8EEENS_9allocatorIS2_EEEC2ERKS5_ + 0x143
    rbp = 0x0000700004ea41c0   rsp = 0x0000700004ea40b0
    rip = 0x000000010793fdd3
    Found by: previous frame's frame pointer
10  CortexService!__ZNSt3__16vectorINS_5arrayIfLm8EEENS_9allocatorIS2_EEEC1ERKS5_ + 0x1d
    rbp = 0x0000700004ea41e0   rsp = 0x0000700004ea41d0
    rip = 0x000000010793e73d
    Found by: previous frame's frame pointer
11  CortexService!__ZNK5rxcpp6detail13OnNextForwardINSt3__16vectorINS2_5arrayIfLm8EEENS2_9allocatorIS5_EEEENS_8subjects6detail18multicast_observerIS8_EEvEclERSC_OS8_ + 0x30
    rbp = 0x0000700004ea4240   rsp = 0x0000700004ea41f0
    rip = 0x000000010793e8a0
    Found by: previous frame's frame pointer
12  CortexService!__ZNK5rxcpp8observerINSt3__16vectorINS1_5arrayIfLm8EEENS1_9allocatorIS4_EEEENS_8subjects6detail18multicast_observerIS7_EEvvvE7on_nextEOS7_ + 0x2c
    rbp = 0x0000700004ea4270   rsp = 0x0000700004ea4250
    rip = 0x000000010793e7bc
    Found by: previous frame's frame pointer
13  CortexService!__ZN5rxcpp10subscriberINSt3__16vectorINS1_5arrayIfLm8EEENS1_9allocatorIS4_EEEENS_8observerIS7_NS_8subjects6detail18multicast_observerIS7_EEvvvEEE12nextdetacherclIS7_EEvT_ + 0x52
    rbp = 0x0000700004ea4300   rsp = 0x0000700004ea4280
    rip = 0x000000010793e5f2
    Found by: previous frame's frame pointer
14  CortexService!__ZNK5rxcpp10subscriberINSt3__16vectorINS1_5arrayIfLm8EEENS1_9allocatorIS4_EEEENS_8observerIS7_NS_8subjects6detail18multicast_observerIS7_EEvvvEEE7on_nextIRS7_EEvOT_ + 0x61
    rbp = 0x0000700004ea4370   rsp = 0x0000700004ea4310
    rip = 0x000000010793e0b1
    Found by: previous frame's frame pointer
15  CortexService!__ZZN5rxcpp9operators6detail25buffer_with_time_or_countINSt3__15arrayIfLm8EEENS3_6chrono8durationIxNS3_5ratioILl1ELl1000EEEEENS_19identity_one_workerEE34buffer_with_time_or_count_observerINS_10subscriberINS3_6vectorIS5_NS3_9allocatorIS5_EEEENS_8observerISI_NS_8subjects6detail18multicast_observerISI_EEvvvEEEEE14produce_bufferEiNS6_10time_pointINS6_12steady_clockENS7_IxNS8_ILl1ELl1000000000EEEEEEENS3_10shared_ptrINSQ_43buffer_with_time_or_count_subscriber_valuesEEEENKUlRKNS_10schedulers11schedulableEE_clES12_ + 0xa9
    rbp = 0x0000700004ea45f0   rsp = 0x0000700004ea4380
    rip = 0x000000010793dc19
    Found by: previous frame's frame pointer
16  CortexService!__ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN5rxcpp9operators6detail25buffer_with_time_or_countINS_5arrayIfLm8EEENS_6chrono8durationIxNS_5ratioILl1ELl1000EEEEENS3_19identity_one_workerEE34buffer_with_time_or_count_observerINS3_10subscriberINS_6vectorIS8_NS_9allocatorIS8_EEEENS3_8observerISL_NS3_8subjects6detail18multicast_observerISL_EEvvvEEEEE14produce_bufferEiNS9_10time_pointINS9_12steady_clockENSA_IxNSB_ILl1ELl1000000000EEEEEEENS_10shared_ptrINST_43buffer_with_time_or_count_subscriber_valuesEEEEUlRKNS3_10schedulers11schedulableEE_S15_EEEvDpOT_ + 0x4d
    rbp = 0x0000700004ea4640   rsp = 0x0000700004ea4600
    rip = 0x000000010793db5d
    Found by: previous frame's frame pointer
17  CortexService!__ZNSt3__110__function6__funcIZN5rxcpp9operators6detail25buffer_with_time_or_countINS_5arrayIfLm8EEENS_6chrono8durationIxNS_5ratioILl1ELl1000EEEEENS2_19identity_one_workerEE34buffer_with_time_or_count_observerINS2_10subscriberINS_6vectorIS7_NS_9allocatorIS7_EEEENS2_8observerISK_NS2_8subjects6detail18multicast_observerISK_EEvvvEEEEE14produce_bufferEiNS8_10time_pointINS8_12steady_clockENS9_IxNSA_ILl1ELl1000000000EEEEEEENS_10shared_ptrINSS_43buffer_with_time_or_count_subscriber_valuesEEEEUlRKNS2_10schedulers11schedulableEE_NSI_IS15_EEFvS14_EEclES14_ + 0x39
    rbp = 0x0000700004ea4680   rsp = 0x0000700004ea4650
    rip = 0x000000010793da39
    Found by: previous frame's frame pointer
18  CortexService!__ZNKSt3__18functionIFvRKN5rxcpp10schedulers11schedulableEEEclES5_ + 0x8e
    rbp = 0x0000700004ea46c0   rsp = 0x0000700004ea4690
    rip = 0x000000010785399e
    Found by: previous frame's frame pointer
19  CortexService!__ZN5rxcpp10schedulers6detail19action_tailrecurserclERKNS0_11schedulableERKNS0_7recurseE + 0xa0
    rbp = 0x0000700004ea4730   rsp = 0x0000700004ea46d0
    rip = 0x00000001078537a0
    Found by: previous frame's frame pointer
20  CortexService!__ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRN5rxcpp10schedulers6detail19action_tailrecurserERKNS4_11schedulableERKNS4_7recurseEEEEvDpOT_ + 0x6d
    rbp = 0x0000700004ea47a0   rsp = 0x0000700004ea4740
    rip = 0x00000001078536ed
    Found by: previous frame's frame pointer
21  CortexService!__ZNSt3__110__function6__funcIN5rxcpp10schedulers6detail19action_tailrecurserENS_9allocatorIS5_EEFvRKNS3_11schedulableERKNS3_7recurseEEEclESA_SD_ + 0x49
    rbp = 0x0000700004ea47f0   rsp = 0x0000700004ea47b0
    rip = 0x00000001078533b9
    Found by: previous frame's frame pointer
22  CortexService!__ZNKSt3__18functionIFvRKN5rxcpp10schedulers11schedulableERKNS2_7recurseEEEclES5_S8_ + 0xb2
    rbp = 0x0000700004ea4850   rsp = 0x0000700004ea4800
    rip = 0x0000000107807d92
    Found by: previous frame's frame pointer
23  CortexService!__ZN5rxcpp10schedulers6detail11action_typeclERKNS0_11schedulableERKNS0_7recurseE + 0x53
    rbp = 0x0000700004ea4890   rsp = 0x0000700004ea4860
    rip = 0x0000000107807cd3
    Found by: previous frame's frame pointer
24  CortexService!__ZNK5rxcpp10schedulers6actionclERKNS0_11schedulableERKNS0_7recurseE + 0x30
    rbp = 0x0000700004ea48c0   rsp = 0x0000700004ea48a0
    rip = 0x0000000107807c50
    Found by: previous frame's frame pointer
25  CortexService!__ZNK5rxcpp10schedulers11schedulableclERKNS0_7recurseE + 0x52
    rbp = 0x0000700004ea4900   rsp = 0x0000700004ea48d0
    rip = 0x00000001078040d2
    Found by: previous frame's frame pointer
26  CortexService!__ZZN5rxcpp10schedulers10new_thread10new_workerC1ENS_22composite_subscriptionERNSt3__18functionIFNS4_6threadENS5_IFvvEEEEEEENKUlvE0_clEv + 0x65e
    rbp = 0x0000700004ea4c20   rsp = 0x0000700004ea4910
    rip = 0x00000001078031fe
    Found by: previous frame's frame pointer
27  CortexService!__ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN5rxcpp10schedulers10new_thread10new_workerC1ENS3_22composite_subscriptionERNS_8functionIFNS_6threadENS8_IFvvEEEEEEEUlvE0_EEEvDpOT_ + 0x2d
    rbp = 0x0000700004ea4c50   rsp = 0x0000700004ea4c30
    rip = 0x0000000107802b8d
    Found by: previous frame's frame pointer
28  CortexService!__ZNSt3__110__function6__funcIZN5rxcpp10schedulers10new_thread10new_workerC1ENS2_22composite_subscriptionERNS_8functionIFNS_6threadENS7_IFvvEEEEEEEUlvE0_NS_9allocatorISE_EES9_EclEv + 0x29
    rbp = 0x0000700004ea4c80   rsp = 0x0000700004ea4c60
    rip = 0x0000000107802a69
    Found by: previous frame's frame pointer
29  CortexService!__ZNKSt3__18functionIFvvEEclEv + 0x7b
    rbp = 0x0000700004ea4cb0   rsp = 0x0000700004ea4c90
    rip = 0x00000001076c00bb
    Found by: previous frame's frame pointer
30  CortexService!__ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEENS_8functionIFvvEEEEEEEEPvSB_ + 0x205
    rbp = 0x0000700004ea4ef0   rsp = 0x0000700004ea4cc0
    rip = 0x00000001077f92c5
    Found by: previous frame's frame pointer
31  libsystem_pthread.dylib + 0x36c1
    rbp = 0x0000700004ea4f20   rsp = 0x0000700004ea4f00
    rip = 0x00007fff5a7f66c1
    Found by: previous frame's frame pointer
32  libsystem_pthread.dylib + 0x356d
    rbp = 0x0000700004ea4f50   rsp = 0x0000700004ea4f30
    rip = 0x00007fff5a7f656d
    Found by: previous frame's frame pointer
33  libsystem_pthread.dylib + 0x2c5d
    rbp = 0x0000700004ea4f78   rsp = 0x0000700004ea4f60
    rip = 0x00007fff5a7f5c5d
    Found by: previous frame's frame pointer
34  CortexService!__ZNSt3__16threadC2INS_8functionIFvvEEEJEvEEOT_DpOT0_ + 0xaf0
    rsp = 0x0000700004ea5028   rip = 0x00000001077f90c0
    Found by: stack scanning

**Comment by kirkshoop** [comment]
Hi!

I can probably say more if you share the code for this expression.

rxcpp has chosen some tradeoffs that are common in C++. it is not thread-safe by default, and it is possible to pass pointers and references to a scope beyond their lifetime. 

I suspect that this is a threading or lifetime issue (or both). 

threading issues usually take the form of having a merge-type or time-type operator where the scheduler/coordinator is not changed from the default. The default is fine when all the sources feeding that operator are fed from the same thread (say UX events), but a thread-safe scheduler must be set explicitly when the sources are produced by different threads.

lifetime issues usually occur when value are captured by reference in a lambda or when pointers are passed around. very similar to the issues that cause lifetime issues in any C++ code.

I am sure we can figure this one out.

**Comment by nguoithichkhampha** [comment]
This is my code. I think it is threading issue because value captured by copy in lambda.
`
StreamPerformanceMetric getPerformanceMetricStream(unsigned int userId,bool isHighRes){
    /*****************time, "int", "fru", "rel", "exc", "eng", "lex", "foc" ***************/
    auto trigger = rxcpp::observable<>::timer(std::chrono::steady_clock::now());
    std::chrono::milliseconds period;
    //std::chrono::milliseconds skip;
    if(isHighRes)
    {
        period = 500ms;
        //skip = 500ms;
    }
    else
    {
        period = 10000ms;
        //skip   = 10000ms;
    }
    auto sc = rxcpp::schedulers::make_current_thread();
    auto so = rxcpp::synchronize_in_one_worker(sc);
    auto p = getEmoEngineEventsStreamWithReplay().skip_until(trigger).filter([userId](auto const & stateAndEvent){
        EmoEventStructData event = stateAndEvent.first;
        unsigned int userID_to_check;
        IEE_EmoEngineEventGetUserId(event.second.get(), &userID_to_check);
        return (IEE_EmoEngineEventGetType(event.second.get()) == IEE_EmoStateUpdated && userID_to_check == userId);
    }).map([](auto const &stateAndEvent){
        std::unique_ptr<void, void (*)(void *)> eState(IEE_EmoStateCreate(), &IEE_EmoStateFree);
        EmoEventStructData event = stateAndEvent.first;
        IEE_EmoEngineEventGetEmoState(event.second.get(),eState.get());

        std::array<float,NUMBER_PM_VALUE + 1> list_value = {0,0,0,0,0,0,0,0};
        list_value[0] = IS_GetTimeFromStart(eState.get());
        list_value[1] = IS_PerformanceMetricGetInterestScore(eState.get());
        list_value[2] = IS_PerformanceMetricGetStressScore(eState.get());
        list_value[3] = IS_PerformanceMetricGetRelaxationScore(eState.get());
        list_value[4] = IS_PerformanceMetricGetInstantaneousExcitementScore(eState.get());
        list_value[5] = IS_PerformanceMetricGetEngagementBoredomScore(eState.get());
        list_value[6] = IS_PerformanceMetricGetExcitementLongTermScore(eState.get());
        list_value[7] = IS_PerformanceMetricGetFocusScore(eState.get());

        return list_value;
    }).buffer_with_time_or_count(period,100,so) | rxo::publish() | rxo::ref_count();
    return p;
}

getPerformanceMetricStream().map([subscriptionId](auto const &data) {
                            if(!data.size()) return Emotiv::Cortex::JsonObject(nullptr);
                            std::array<float, NUMBER_PM_VALUE + 1> last_value = data.back();
                            float last_time = last_value[0];
                            std::size_t buffer_size = data.size();
                            std::vector<float> average_value(NUMBER_PM_VALUE, 0.0f);

                            for (int i = 0; i < NUMBER_PM_VALUE; ++i) {
                                float sum_of_value = std::accumulate(data.begin(), data.end(), 0.0f,
                                                                     [i](float init_value, auto &p) {
                                                                         return init_value + p[i + 1];
                                                                     });
                                if (sum_of_value > 0)
                                    average_value[i] = sum_of_value / buffer_size;
                            }
                            nlohmann::json jsonData =
                                    {{"sid",  std::move(subscriptionId.get())},
                                     {"time", nlohmann::json(last_time)},
                                     {"met",  nlohmann::json(std::move(average_value))}
                                    };

                            return Emotiv::Cortex::JsonObject(std::move(jsonData));
                        }).
                                subscribe_on(rxcpp::observe_on_new_thread()).
                                subscribe(std::move(onNext),
                                          std::move(onError),
                                          std::move(onCompleted))
`

**Comment by kirkshoop** [comment]
Hi!

I do not see the thread context for the `getEmoEngineEventsStreamWithReplay()` source, but here is a suggestion.  change `sc` to be a new thread scheduler and move the `sc` & `so` declarations to the top and pass `so` to the `trigger`-`timer`, `skip_until` and `subscribe_on` operators.

from a thread perspective:

- `trigger` defaults to the `current_thread` scheduler, so it will be influenced by the thread context that `subscribe` is called from.
- `skip_until()` merges the `trigger` and `getEmoEngineEventsStreamWithReplay()` sources. `skip_until` defaults to the `current_thread` scheduler to coordinate the two sources. if these sources are from different threads, that coordination will fail with undefined behavior. this is fixed by passing a thread-safe scheduler to `skip_until`
- `make_current_thread()` returns the default `current_thread` scheduler. `current_thread is a thread-local trampoline scheduler to protect the stack from infinite recursion. this means that it checks a thread-local-slot to see if the thread has a queue and sets a queue into the slot if it was empty or pushes the work into the queue if it was not empty. As a result using this scheduler will always reschedule on the same thread. If two sources use this from two threads, then `current_thread` will not coordinate the two threads safely.
- `synchronize_in_one_worker()` will allow a single `new_thread` to be shared between multiple operators. It has no effect on the `current_thread` scheduler since that uses the thread-local-slot pick a different scheduler for each thread that calls.
- `buffer_with_time_or_count()` defaults to the `current_thread` scheduler. the scheduler is used to coordinate the time interval source with the values source. using the `current_thread` requires that the subscribe and the values source are on the same thread.
- `subscribe_on()` will call subscribe on the scheduler. in the case of the `new_thread` scheduler a new thread is created and subscribe is called from the new thread. when that call to subscribe returns the thread is destroyed.

**Comment by nguoithichkhampha** [comment]
Hi @kirkshoop , Thanks for your suggestion . Do you mean problem because don't set `so` in operator ? 
here is code of getEmoEngineEventsStreamWithReplay:
`StreamEmoEvent & getEmoEngineEventsStreamWithReplay() {
    static StreamEmoEvent engineEvents = rxs::interval(100ms).map([](auto value) {
        std::shared_ptr<void> evt(IEE_EmoEngineEventCreate(), &IEE_EmoEngineEventFree);
        try {
            auto state = IEE_EngineGetNextEvent(evt.get());
            return std::make_pair(state, std::move(evt));
        }
        catch (std::exception &e)
        {
            std::cerr << "Catch exception in function getEmoEngineEventsStreamWithReplay " << e.what() << std::endl;
            return std::make_pair(static_cast<int>(EDK_UNKNOWN_ERROR), std::move(evt));
        }
    }).filter([](auto const & stateAndEvent) {
        return stateAndEvent.first == EDK_OK;
    }).timestamp().replay() | rxo::ref_count();
    return engineEvents;
}`

**Comment by nguoithichkhampha** [comment]
I resolved the issue, thanks for your support.
