### ISSUE TITLE
combine observables from different scopes

### ISSUE THREAD

**Issue by pietercardoen** [ReactiveX/RxCpp#419]
Hello

I am using a library which can be initiated and uses a callback to to inform the application that a message is received. How can I instantiate an observable in the callback function and use it in the main loop?

i.e.:

void callback(){
      push an event to an observer in the main loop
}

int main(){

      initLibrary(callback);

      // Observe here the observable in the callback function

}

**Comment by kirkshoop** [comment]
here is an example of how to tie libuv fs callbacks to rxcpp.

```
// wrap up uv filesystem requests as observables
template<typename F>
auto rx_uv_fs_request(F&& f) {
    return create<uv_fs_t*>([f](auto out) {

        // observables are lazy, this is a COLD observable
        // each call to subscribe will open the file.
        // build the per-subscribe state
        struct uv_request_state {
            explicit uv_request_state(subscriber<uv_fs_t*> o) : out(move(o)) {}
            ~uv_request_state() {
                uv_fs_req_cleanup(&request);
            }
            uv_fs_t request;
            subscriber<uv_fs_t*> out;
        };
        // not ideal, would like to remove these allocations
        auto state = make_unique<uv_request_state>(out.as_dynamic());
        state->request.data = state.get();

        auto req = const_cast<uv_fs_t*>(&state->request);

        // call the function with a callback and the request dedicated to this call
        int result = f(req, [](uv_fs_t* req){
            // take over the lifetime of the state
            unique_ptr<uv_request_state> state(static_cast<uv_request_state*>(req->data));
            req->data = nullptr;

            if (report_fail(req->result, state->out)) {
                return;
            }

            state->out.on_next(req);
            state->out.on_completed();
            return;
        });
        if (report_fail(result, state->out)) {
            // the callback will not be called, cleanup the state
            return;
        }
        // the callback will be called, defer lifetime to the callback
        state.release();
    });
}

auto rx_uv_fs_close(uv_loop_t* loop,
                          uv_file file){
    return rx_uv_fs_request([loop, file](uv_fs_t* req, uv_fs_cb cb){
        return uv_fs_close(loop, req, file, cb);
    });
}
```

**Comment by pietercardoen** [comment]
Hello

Thanks for the example. I however notice that you use a lambda without variable capture. I would like to replace:
int result = f(req, [](uv_fs_t* req){ ...

by 

int result = f(req, [&](uv_fs_t* req){ ...

However I get a number of type errors because it's not possible to cast the lambda type to the function type.

Best regards
Pieter

**Comment by kirkshoop** [comment]
Yes, the callback must allow a pointer to be stored in the request so that some state can be allocated and stored in the request and used on the callback so that no captures are required in the lambda.

Or worse, there must be some shared global that is used to pass the state to the callback.
