### ISSUE TITLE
observe_on requires equal-to operator ?

### ISSUE THREAD

**Issue by nikobarli** [ReactiveX/RxCpp#420]
Hi, 

The following codes 

```
        struct Obj {
        };

        std::vector<Obj> input;
        auto src = rxcpp::observable<>::just<std::vector<Obj>>(input).as_dynamic();
        auto c = rxcpp::observe_on_new_thread();
        src.observe_on(c).as_blocking().subscribe([](auto && val){});

```

gives the followin compile error (on VS2015).

> Error	C2672	'operator __surrogate_func': no matching overloaded function found
> Error	C2893	Failed to specialize function template 'unknown-type std::equal_to<void>::operator ()(_Ty1 &&,_Ty2 &&) const'

The error is caused by the 'observe_on' operator and disappears if I add equal-to operator to the struct Obj. 

```
bool operator==(const Obj& lhs, const Obj& rhs) {
    return true;
}

```
Is it intended behavior ?

**Comment by kirkshoop** [comment]
Hi!

This is a side-effect that is expected, but perhaps, not required.

`observe_on` uses a queue of `notification` to pass the calls from one context to another. A `notification` is a virtual object with implementations for each of the observer methods. The notification is used by the `materialize` operator as well.

The on_next implementation of the `notification` stores a value and supports all the copy/move operations.

It might be possible to use copy/move construction at every point in the `observe_on` code path, but I have not tried. This might remove the need for operator=

**Comment by nikobarli** [comment]
Thanks for the answer. Need to dig and understand rxcpp code to really understand it. Hope can have more time to study it and maybe help fixing the issues instead of just reporting them :)

**Comment by kirkshoop** [comment]
PRs always welcome, but issues are also important contributions, Thanks!

**Comment by bdbai** [comment]
Hi there! Recently I have encountered the same issue. Would it be nice to state the requirement (or pitfall) in the documentation? Thanks!
