### ISSUE TITLE
use observable in different scope

### ISSUE THREAD

**Issue by pietercardoen** [ReactiveX/RxCpp#421]
Hello

I want to use an observable for the state of an algorithm and want it to be available to multiple observables in different scopes (i.e. a callback function and a main loop). How do you handle this? Do you have an example on this?

Thanks

**Comment by kirkshoop** [comment]
an observable is a value and can be copied into multiple scopes. The behavior of the copies depends on the observable itself. a search for HOT vs COLD observables will describe the differences and how to turn one into the other (eg, use subjects via publish or replay).
