### ISSUE TITLE
observables subscribed to eachother

### ISSUE THREAD

**Issue by pietercardoen** [ReactiveX/RxCpp#423]
I have an algorithm which monitors two services (observable 1 and 2). These services initiated in observables which are merged together. Is it possible to have an observable in this algorithm (observable 3) which is observed by the service monitoring observables? I would like to allow the main algorithm to disable the services which are monitored in observable 1 and 2.

**Comment by kirkshoop** [comment]
One way is demonstrated in the twitter app.

The `useSentimentApi` defined here:
https://github.com/kirkshoop/twitter/blob/master/main.cpp#L435-L452

is used to control `sentimentupdates` here:
https://github.com/kirkshoop/twitter/blob/master/main.cpp#L783-L789

**Comment by pietercardoen** [comment]
I am trying to figure out what's going on in the example you gave but I must say that it looks impossible to me to understand what's going on... Don't you have a more simple example on this?

**Comment by kirkshoop** [comment]
I have not compiled this, but here is the simplified example.

```cpp
// data
auto observable1 = interval(200ms) | publish() | connect_forever();
auto observable2 = interval(500ms) | publish() | connect_forever();

// toggle a bool every 2 seconds
auto observable3 = interval(2s) | map([](int tick){ return tick % 2 == 0; });

observable3 |
  rxo::map([=](bool use){
    // if the toggle is on subscribe to the merged data
    // if the toggle is off subscribe to empty observable
    return use ? observable1 | merge(observable2) : empty<int>() | as_dynamic();
  }) |
  // only subscribe to the latest observable returned from map.
  switch_on_next() |
  subscribe();
```
