### ISSUE TITLE
Possibility for new Release-Tag

### ISSUE THREAD

**Issue by juxeii** [ReactiveX/RxCpp#425]
Hello,

a great library :-)
I wanted to ask for a new release tag, since I have issues with the `timeout` operator.
I'm using tag 4.0.0 but there is still this bug in:
[https://github.com/Reactive-Extensions/RxCpp/commit/5aea424898994b3d409db268486202244cfe5053](url)

Is there any chance that there will be a new tag in the foreseeable future?

Thx,
Juergen

**Comment by kirkshoop** [comment]
Yes, I will plan this for February.

**Comment by juxeii** [comment]
Any news on this?

**Comment by kirkshoop** [comment]
I missed my deadline, I will schedule time for this soon. Thanks for the prompt!

**Comment by kirkshoop** [comment]
The new tag is [4.1.0](https://github.com/ReactiveX/RxCpp/tree/4.1.0)
