### ISSUE TITLE
Why is the repo size so large?

### ISSUE THREAD

**Issue by paulreimer** [ReactiveX/RxCpp#427]
65 MB for a full clone, but only ~3 MB when checked out?

Might be worth cleaning up the history (rebase, prune, archive the current history into a new repo etc?)

I'll vendor it anyway (or do a shallow clone) for CI but I would have preferred to use a submodule (but it takes a while to fetch the full history).

**Comment by kirkshoop** [comment]
I would guess that the history includes the Ix.Net, Rx.Net and perhaps even RxJs before the repo was split by language. If it would reduce the size of a clone to break history in master while keeping the complete history in a separate branch, I would like that, but I fear that the history would have to be deleted from every branch to reduce the size of a clone..

**Comment by paulreimer** [comment]
Yup, unfortunately that's the only way I've ever seen it done (either duplicating and/or archiving/renaming the old source somewhere). (and it isn't fun for anyone with existing clones of the current history, but a `master` rebase would have that same effect). Not sure what to do, personally I'm vendor'ing a copy of the latest `RxCpp` sources so that kind of sidesteps the issue.
