### ISSUE TITLE
inefficient implementation of blocking_subscribe

### ISSUE THREAD

**Issue by nikobarli** [ReactiveX/RxCpp#430]
When debugging an issue, I found that the implementation of blocking_subscribe inside rx-observable.hpp is a bit weird. The predicate lambda passed to std::condition_variable::wait is polling a memory location:

```cpp
        cs.add(
            [&, track](){
                // OSX geting invalid x86 op if notify_one is after the disposed = true
                // presumably because the condition_variable may already have been awakened
                // and is now sitting in a while loop on disposed
                wake.notify_one();
                track->disposed = true;
            });

        std::unique_lock<std::mutex> guard(lock);
        source.subscribe(std::move(scbr));

        wake.wait(guard,
            [&, track](){
                // this is really not good.
                // false wakeups were never followed by true wakeups so..

                // anyways this gets triggered before disposed is set now so wait.
                while (!track->disposed) {
                    ++track->false_wakes;
                }
                ++track->true_wakes;
                return true;
            });
```

Looking at the comment, and the diff with the previous revision, I understood that you made the modification due to some problem in OSX environment. 

Below is the code from the previous revision.

```cpp
        std::mutex lock;
        std::condition_variable wake;
        std::atomic_bool disposed;
        auto scbr = make_subscriber<T>(std::forward<ArgN>(an)...);
        auto cs = scbr.get_subscription();
        cs.add([&](){
            disposed = true;
            wake.notify_one();
        });

        std::unique_lock<std::mutex> guard(lock);
        source.subscribe(scbr);
        wake.wait(guard, [&](){return !!disposed;});

```

Looking at this older code, I suspect the original problem you experienced in IOS is because a race condition: 

> Thread 1: get lock and subscribe
> Thread 1: check (!!disposed) -> false, needs to wait for conditional_variable
> Thread 2: set disposed = true
> Thread 2: wake.notify_one();
> Thread 1: enter wait() ->  never gets notified

I think a better approach to solve this is to lock the same mutex inside the unsubscription handler. And you actually don't need the "disposed" flag.

```cpp
        auto cs = scbr.get_subscription();
        cs.add(
            [&](){
                {
                    // Just make sure to acquire the lock once before notifying.
                    // This guarantee the subscriber has enter wake.wait().
                    std::unique_lock<std::mutex> guard(lock);
                }
                wake.notify_one();
            });

        std::unique_lock<std::mutex> guard(lock);
        source.subscribe(std::move(scbr));
        wake.wait(guard);

```

**Comment by nikobarli** [comment]
BTW, because the implementation of wait(_Lck, _Pred) in MSVC is as follows:

```cpp
	template<class _Predicate>
		void wait(unique_lock<mutex>& _Lck, _Predicate _Pred)
		{	// wait for signal and test predicate
		while (!_Pred())
			wait(_Lck);
		}

```

The current implementation will just busy-wait inside _Pred() and never really waits for the conditional variable.

**Comment by kirkshoop** [comment]
Hi!

taking the mutex in the `unsubscribe` is going to require `recursive_mutex` since the unsubscribe could be called from thread 1.

RE MSVC: won't `wait(_Lck)` wait for the condition?

**Comment by nikobarli** [comment]
> taking the mutex in the unsubscribe is going to require recursive_mutex since the unsubscribe could be called from thread 1.

Ah yes. Forgot that scenario. Need to use recursive_mutex, or use flag as before and lock after subscribe is called:

```cpp
        auto cs = scbr.get_subscription();
        bool disposed = false;
        cs.add(
            [&](){
                {
                    // Just make sure to acquire the lock once before notifying.
                    // This guarantee the subscriber has enter wake.wait().
                    std::unique_lock<std::mutex> guard(lock);
                    disposed = true;
                }
                wake.notify_one();
            });

        source.subscribe(std::move(scbr));

        std::unique_lock<std::mutex> guard(lock);
        wake.wait(guard, [&](){return !!disposed;});
```

> RE MSVC: won't wait(_Lck) wait for the condition?

The current implementation of _Pred is as follows. It always return true (after busy-wait), thus wait(_Lck) is never called.

```cpp
            [&, track](){
                // this is really not good.
                // false wakeups were never followed by true wakeups so..

                // anyways this gets triggered before disposed is set now so wait.
                while (!track->disposed) {
                    ++track->false_wakes;
                }
                ++track->true_wakes;
                return true;
            });

```

**Comment by kirkshoop** [comment]
> It always return true (after busy-wait), thus wait(_Lck) is never called.

yep, that is bad.

> use flag as before and lock after subscribe is called

Yes, I prefer that. It will need stress testing on multiple platforms to make sure that it behaves.

> // This guarantee the subscriber has enter wake.wait().

I do not think this guarantee holds here because the subscribe is not under the lock and the call to subscribe could occur before the subscribe returns..

**Comment by nikobarli** [comment]
> // This guarantee the subscriber has enter wake.wait().
> 
> I do not think this guarantee holds here because the subscribe is not under the lock and the call to subscribe could occur before the subscribe returns..

Yes you are right. We should use the solution with the 'disposed' flag instead.
