### ISSUE TITLE
Visual Studio 2015 IntelliSense with RXCPP

### ISSUE THREAD

**Issue by vladsterz** [ReactiveX/RxCpp#431]
IntelliSense is not working,
Simple example
`auto ints = rx::observable<>::create<int>([](rx::subscriber<int> s) {
		s.on_next(1);
		s.on_next(2);
		s.on_completed();
	});`
"No instance of function template error ......" is present on the editor but the the code itself builds and runs normally.

**Comment by kirkshoop** [comment]
yes, visual studio currently uses the EDG compiler for intellisense. Since it is a completely different compiler it often disagrees with the visual studio compiler.
