### ISSUE TITLE
Question about coordination

### ISSUE THREAD

**Issue by nikobarli** [ReactiveX/RxCpp#434]
Hi,

I am trying to understand the different types of coordination in the current rxcpp by reading https://github.com/Reactive-Extensions/RxCpp/blob/master/DeveloperManual.md, but I don't quite understand yet the difference between between:

rxcpp::observe_on_* 

and

rxcpp::serialize_*

When should I use observe_on_* and when should I use serialize_* ?

thanks.

**Comment by kirkshoop** [comment]
Hi!

These are both coordinators that are layered on top of schedulers. The operators offload thread-safe coordination to these coordinators. in the case of merge, each incoming observable is passed through the coordinator to get a coordinated observable that shares a context.

the observe_on coordinator uses a shared queue and the layered scheduler to transport work to a single destination thread. 

serialize coordinator uses a shared mutex to serialize calls to on_next, on_error, on_completed and to the scheduled items on the layered scheduler.

Does this help?
