### ISSUE TITLE
RxCpp and QT integration : any documentation?

### ISSUE THREAD

**Issue by renaudcerrato** [ReactiveX/RxCpp#438]
Just moved from Android to QT, and I'm struggling integrating RxCpp with the QT events loop. I'm basically trying to obtain a scheduler similar to `AndroidSchedulers.mainThread()`. 

Reading through #154 and #337 (thanks @studoot), I found the undocumented `set_notify_earlier_wakeup`. 

I managed to get this far :

```cpp
#include "rxcpp/rx.hpp"
namespace rx=rxcpp;

class helper
{
 public:
   helper(QObject *parent = Q_NULLPTR) : timer(parent)
   {
      rl.set_notify_earlier_wakeup([&](std::chrono::steady_clock::time_point when)
      {
         // Tell the timer to wake-up at `when` if its not already waking up earlier
         const auto ms = ms_until(when).count();
         if (!timer.isActive() || ms < timer.remainingTime())
         {
            timer.start(ms);
         }
      });
      timer.setSingleShot(true);
      timer.setTimerType(Qt::PreciseTimer);
      timer.connect(&timer, &QTimer::timeout, [&]() { onEventScheduled(); });
   }

   rxcpp::schedulers::run_loop rl;

private:
   // Flush the RxCpp run loop
   void onEventScheduled()
   {
      // Dispatch outstanding RxCpp events
      while (!rl.empty() && rl.peek().when < rl.now())
      {
         rl.dispatch();
      }
      // If there are outstanding events, set the timer to wakeup for the first one
      if (!rl.empty())
      {
         const auto time_till_next_event = ms_until(rl.peek().when);
         timer.start(static_cast<int>(time_till_next_event.count()));
      }
   }

   std::chrono::milliseconds ms_until(rxcpp::schedulers::run_loop::clock_type::time_point const& when) const
   {
      return ceil<std::chrono::milliseconds>(when - rl.now());
   }

   template <class To, class Rep, class Period>
   static inline To ceil(const std::chrono::duration<Rep, Period>& duration)
   {
      const auto as_To = std::chrono::duration_cast<To>(duration);
      return (as_To < duration) ? (as_To + To{1}) : as_To;
   }

   QTimer timer;
};

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    helper rl;

    std::cout << std::setw(16) << std::this_thread::get_id() << " <- main thread id" << std::endl;

    using namespace std::chrono;

    auto mainthread = rx::observe_on_run_loop(rl.rl);
    auto workthread = rx::synchronize_new_thread();

    rx::composite_subscription lifetime;

    rx::observable<>::interval(workthread.now() + milliseconds(100), milliseconds(400)).
        map([](int i){
            std::cout << std::setw(16) << std::this_thread::get_id() << ": " << i << std::endl;
            return i;
        }).
        take_until(rx::observable<>::timer(seconds(1))).
        subscribe_on(workthread).
        observe_on(mainthread).
        subscribe(lifetime, [&](int i){
            std::cout << std::setw(16) << std::this_thread::get_id() << ": " << i << std::endl;
        });

    return a.exec();
}
```

Unfortunately, I'm getting the following output:

```shell
5080 <- main thread id
11864: 1
QObject::startTimer: Timers cannot be started from another thread
11864: 2
11864: 3
```

I'm rather new to QT, and it sounds like I can't start a timer on a different thread from which it has been created. Any idea on how to do a proper integration?

**Comment by renaudcerrato** [comment]
Stupid me : replacing `timer.start(ms)` with `QMetaObject::invokeMethod(&timer, "start", Qt::AutoConnection, Q_ARG(int, ms))` will do the trick. Is there any more straightforward solution I missed?

**Comment by anatoly-spb** [comment]
@renaudcerrato You can find interesting for yourself the rxqt project (see https://github.com/tetsurom/rxqt)  I have wrote more universal adapter for my project based on the rxqt project: https://github.com/anatoly-spb/qtimageviewer/blob/rxcpp/rxeventloop.h Fill free to use it for your own purpores.

**Comment by renaudcerrato** [comment]
Thanks @anatoly-spb ! But it seems that your `RxEventLoopAdapter` is having the same issue I'm facing : you're calling `QTimer::start()` within the `set_notify_earlier_wakeup` [callback](https://github.com/anatoly-spb/qtimageviewer/blob/rxcpp/rxeventloop.h#L39). Using my example above, you'll end up with a `QObject::startTimer: Timers cannot be started from another thread`. Am I missing something?

**Comment by anatoly-spb** [comment]
@renaudcerrato timer must be created in a event loop thread. Neight mainthread nor workthread does not have Qt Event Loop to process timer event. Look at this example: https://github.com/anatoly-spb/qtimageviewer/blob/rxcpp/imagelistview.cpp#L49

**Comment by renaudcerrato** [comment]
I see. Thanks for the clarifications !

**Comment by anatoly-spb** [comment]
@renaudcerrato here is small example:
```
#include "mainwindow.h"
#include "rxeventloop.h"

#include <QApplication>
#include <QDebug>

#include <thread>

int main(int argc, char* argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    rxcpp::observable<>::interval(std::chrono::milliseconds(1000))
        .take(10)
        .observe_on(rxcpp::observe_on_run_loop(RxEventLoopAdapter::runLoop()))
        .subscribe([](long value) {
            // observed on Qt Main Event Loop
            qDebug() << value;
        });
    return a.exec();
}
```

**Comment by anatoly-spb** [comment]
@renaudcerrato it seems to me I have reproduced your problem. Here is fixed version of rxeventloop.h with demo main.cpp: https://gist.github.com/anatoly-spb/0d64d1022e2c5c9d17491d2c0e3a9346

**Comment by renaudcerrato** [comment]
Thanks. That's exactly what I pointed out and suggested in my second post 🙂
