### ISSUE TITLE
odd behavior of combine_latest().observe_on(mainthread)

### ISSUE THREAD

**Issue by jjhegedus** [ReactiveX/RxCpp#446]
I have a couple of types which do not support the == operator

```
    struct DirectXVertexShader {
        int id;
        std::wstring fileName;
        winrt::com_ptr<ID3D11VertexShader> shader;
        std::vector<::byte> shaderFileData;
    };
```

and 

```
    struct DirectXPixelShader {
        int id;
        std::wstring fileName;
        winrt::com_ptr<ID3D11PixelShader> shader;
        std::vector<::byte> shaderFileData;
    };
```

and I have two behavior subjects of these types and on next is triggered from asynchronosly loading the shader files

```
rx::subjects::behavior<DirectXVertexShader> fullScreenQuadVertexShaderBehavior{rx::subjects::behavior<DirectXVertexShader>{}};

rx::subjects::behavior<DirectXPixelShader> distanceFieldPixelShaderBehavior{rx::subjects::behavior<DirectXPixelShader>{}};
```

when I use these with combine latest to dispatch an action after both receive data as in the following.  They work fine.

```
distanceFieldPixelShaderObservable.combine_latest(fullScreenQuadVertexShaderObservable).subscribe([textRendererId](auto values) {
                    Dispatcher::Dispatch(ndtechHoloActions::RenderDistanceField(textRendererId));
                });
```

However, when I try to force the observation to happen on the main thread using observe_on(mainthread) like this

```
distanceFieldPixelShaderObservable.combine_latest(fullScreenQuadVertexShaderObservable).observe_on(mainthread).subscribe([textRendererId](auto values) {
                    Dispatcher::Dispatch(ndtechHoloActions::RenderDistanceField(textRendererId));
                });
```

with mainthread defined as follows

```
        rx::schedulers::run_loop                                                m_runLoop;
        rx::observe_on_one_worker                                               mainthread = rx::observe_on_run_loop(m_runLoop);
```

I get the following compile error

`Error	C2678	binary '==': no operator found which takes a left-hand operand of type 'const ndtechHolo::DirectXPixelShader' (or there is no acceptable conversion)	`

Any idea why this might be happening or how I could get around it?  Also, is this approach a bad idea for some reason?

**Comment by jjhegedus** [comment]
I got around the problem by implementing operator== for my types.  I still don't understand why it is necessary.

**Comment by kirkshoop** [comment]
I believe that this is caused by the notification reuse in the observe_on() operator. 

## Workaround: 
you could change to serialize_same_worker and thus avoid the call to observe_on().

## Details:
the materialize and dematerialize operators use a notification to serialize a call to an observer. observe_on() uses this to transport calls to an observer through a scheduler. observe_on_one_worker uses observe_on. the notification requires operator== because it is used to compare notifications from different streams.

**Comment by kirkshoop** [comment]
I glossed over the explicit `.observe_on(mainthread)`

combine_latest() will directly take the mainthread as its first parameter, the explicit observe_on(mainthread) can then be removed. just make sure that the mainthread is a serialize_one_worker, not an observe_on_one_worker

**Comment by jjhegedus** [comment]
Thanks for taking a look at this.  One thing I very much appreciate about this project is that you take answering questions seriously.

I tried to test using serialize_one_worker and it did allow my code to compile without my types implementing operator==.  Unfortunately, it looks like observe_on() was obscuring a bug in my own code that serialize_one_worker exposed.  I was updating one of the observable subjects from within a section of code guarded by a mutex.  The operation I called from the subscribe method requires locking the same mutex.  When I try to lock the mutex again, on_next throws an error.  I'm glad it does and I clearly need to modify my algorithm.

I have some work to do to make the corrections to my logic before I'll be able to completely confirm the fix, though I expect that it will work.  I am curious though, why the situation I created would work with observe_on if you have time to answer yet another question.

**Comment by jjhegedus** [comment]
After updating my logic, I was able to verify that changing to use serialize_one_worker fixed the issue.

**Comment by kirkshoop** [comment]
coordinators do not only serialize work they also have different concurrent behaviors. I did not take into account that you explicitly wanted the work transported to a different thread as opposed to merely synchronized across threads.

observe_on is required to transport the callback to the mainthread. observe_on depends on notification for the queue value_type. 

operator== must exist for observe_on today (it can std::abort when called if that is desired) and notification needs to change to not require operator== (SFINAE comparisons away when the type does not support operator==)

**Comment by kirkshoop** [comment]
hmm. I went to add a test and then add the SFINAE for notification and found that the test worked on OSX and that notification already uses SFINAE for operator==. This appears to be specific to the MSVC compiler. which version are you using?

**Comment by jjhegedus** [comment]
My apologies for not being clearer with my requirements.  I am very new to rxcpp and don't have as much depth with rx in general as I might like.  I don't completely understand the nuances.  I'm not really sure what you mean when you say "merely synchronized across threads."

Visual Studio is version 15.7.3.  cl reports version 19.14.26430.

Thanks again for taking a look at this, though I think I will be OK adding operator== for my types at the moment.  I can see how this might cause difficulties if I was using a type that I don't have control over which might be the case sometime in the future.  I would have submitted a pull request if I could have figured out how to fix this myself, but I hate to admit that when I looked through the code my head was spinning trying to understand the heavy use of template meta-programming.  Maybe someday.

By the way, a slightly off topic question.  Do you have a preferred method for contributing documentation.  I was thinking it might be best just to submit a pull request to https://github.com/ReactiveX/reactivex.github.io to keep the documentation with the rest of the rx documentation.  I don't know how involved you are with that project though so I thought I would ask what you prefer while I have your attention.

**Comment by kirkshoop** [comment]
I know the nuances, but still forget the details!

>  I'm not really sure what you mean when you say "merely synchronized across threads."
using a mutex to make sure that only one method is called at a time even when multiple threads are calling methods on the same object. This is not the same as using a queue to transfer the method call on a different thread.

>  I think I will be OK adding operator== for my types at the moment
Thank you and thank you for this report.

> my head was spinning trying to understand the heavy use of template meta-programming
yes, the internals are cryptic and complex. The purpose is to allow more people to use concurrency safely without needing to understanding the internals

> Do you have a preferred method for contributing documentation
The existing docs are generated by doxygen from comments in the code. Contributions to the existing docs are welcome and I would love to see contributions to begin adding information about rxcpp to the reactivex.io docs!

**Comment by jjhegedus** [comment]
Got it.  Yes, at the moment I have some methods that can be called concurrently from different threads and need to be synchronized.  I expect that as I get a better grasp on the concepts of rx I might be able to find a way around it but for the moment I haven't been able to see a better way.

Now that I understand observe_on and when and how to use it I'll go ahead and close this thread.

Thanks again for all your insights in this thread and I appreciate all you've done to make rxcpp happen.  It's a great project and something I think C++ needed to stay current.  I will plan on submitting some documentation pull requests to reactivex.io as I think having some information there will do a lot to get rxcpp in front of people and make sure they know it's real.
