### ISSUE TITLE
Alternative to using subjects (or behaviors) for (infinite) streams?

### ISSUE THREAD

**Issue by thorstink** [ReactiveX/RxCpp#451]
Hi, 

I am toying around using rxcpp and I am having some difficulties deciding on implementation. Another thing that confuses me is that in a lot of examples observables are finite, while I want to use them in a sort of 'infinite' way. I have multiple continuous sources of information (driver-objects for e.g. sensors) and they all have their own event loop. I want to use observables so I can combine their information and apply functions to them and pass them on. 

So far I implemented subjects (and behaviors, but what is the difference exactly?) and 'manually' call the on_next() function from the subject's subscriber. However, reading [`this`](https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93) implies I should try avoiding this sort of scheme if I can. I have not figured out an alternative way so I am asking here :-) Or is subjects/behavior the appropriate way to go if you want to move information from such a driver to an observable? In other Rx implementations I see a from_event implementation? Is that something that might handle these drivers in a more rx-way?

Also; what I do now is to make the subject a member variables of the specific driver and subscribe to it (through get_observable()) from the parent scope; is that considered normal use? 

I wrote up some minimal working example to demonstrate what I made; I was just wondering if this is sort of among the lines on how RX should be used.. :-)

```cpp
#include<rxcpp/rx.hpp>
#include<thread>
#include<memory>
#include<chrono>
#include<string>
namespace rx=rxcpp;
namespace rxsub=rxcpp::subjects;
namespace rxu=rxcpp::util;
using namespace std::chrono_literals;

class driver {
public:
    driver(int t, std::string msg) : t_(std::chrono::seconds(t)), msg_(msg) {
        b_.reset(new rxcpp::subjects::behavior<std::string>(msg_));
    }
    void run()
    {
        for (;;) {
            b_->get_subscriber().on_next(msg_);
            std::this_thread::sleep_for(t_);  
        }
    }
    std::shared_ptr<rxcpp::subjects::behavior<std::string>> b_;
    std::chrono::seconds t_;
    std::string msg_;
};

class complextask 
{
public:
    complextask(int t) : t_(std::chrono::seconds(t)) {};
    std::string calculate(std::string msg) {
        std::this_thread::sleep_for(t_);
        return std::string("after a lot of thinking: ") + msg;  
    }
    std::chrono::seconds t_;
};

int main()
{
    // generate information
    driver foo(1, "foo");
    driver bar(2, "bar"); 
    // calculation task
    complextask complex(5);

    // give drivers their own thread
    std::thread t_foo([&](){
        foo.run();
    });

    std::thread t_bar([&](){
        bar.run();
    });

    std::cout << "main thread\n";
    auto barobs = bar.b_->get_observable();
    auto fooobs = foo.b_->get_observable();
    auto merged = barobs.merge(fooobs);

    merged.subscribe([](std::string msg){
            std::cout << msg << ", " << std::endl;
        });

    merged
        .observe_on(rxcpp::observe_on_event_loop())
        .subscribe([&](std::string msg){
            std::cout << complex.calculate(msg) << std::endl;
        });

    t_foo.join();
    t_bar.join();
    return 0;
}
```

**Comment by kirkshoop** [comment]
Hi!

There is more than one way to do this. The approach chosen depends on the source of the data.

from_event implementations use a subject to connect an existing callback to an observable. The subject/behavior approach is valid and can be hidden in a function without having to build a separate type per source.

Note: behavior and subject already have value semantics, so the shared_ptr are not needed.
Note: try to put side-effects like cout in subscribe or tap and do the computations in other methods.
Note: try to use existing operators including create rather than raw subjects.
Note: try to use existing operators rather than create

Another approach is to use create.

```cpp

auto driver(int t, std::string msg) {
  return rxcpp::sources::create<std::string>([t, msg](auto out){
    std::thread th([t, msg, out](){
      for (;;) {
        if (!out.is_subscribed()) {return;}
        out.on_next(msg);
        if (!out.is_subscribed()) {return;}
        std::this_thread::sleep_for(std::chrono::seconds(t));  
      }
    });
    th.detach();
    return out.get_subscription();
  });
}

class complextask 
{
public:
    complextask(int t) : t_(std::chrono::seconds(t)) {};
    std::string calculate(std::string msg) {
        std::this_thread::sleep_for(t_);
        return std::string("after a lot of thinking: ") + msg;  
    }
    std::chrono::seconds t_;
};

int main()
{
    // generate information
    auto foo(driver(1, "foo"));
    auto bar(driver(2, "bar")); 
    // calculation task
    complextask complex(5);

    std::cout << "main thread\n";
    auto merged = bar.merge(foo);

    merged.subscribe([](std::string msg){
            std::cout << msg << ", " << std::endl;
        });

    merged
        .observe_on(rxcpp::observe_on_event_loop())
        .map([&](std::string msg){ return complex.calculate(msg);})
        .take(10)
        .blocking_subscribe([](std::string msg){
            std::cout << msg << std::endl;
        });

    return 0;
}
```

it is also possible to use the schedulers to produce the threads.

```cpp

template<class Loop>
auto driver(Loop l, int t, std::string msg) {
  return rxcpp::sources::interval(std::chrono::seconds(t), l)
    .map([](long){return std::string("foo");})
}

class complextask 
{
public:
    complextask(int t) : t_(std::chrono::seconds(t)) {};
    std::string calculate(std::string msg) {
        std::this_thread::sleep_for(t_);
        return std::string("after a lot of thinking: ") + msg;  
    }
    std::chrono::seconds t_;
};

int main()
{
    auto loop = rxcpp::observe_on_event_loop();
    // generate information
    auto foo(loop, 1, "foo");
    auto bar(loop, 2, "bar");
    // calculation task
    complextask complex(5);

    std::cout << "main thread\n";
    auto merged = bar.merge(foo);

    merged.subscribe([](std::string msg){
            std::cout << msg << ", " << std::endl;
        });

    merged
        .observe_on(loop)
        .map([&](std::string msg){ return complex.calculate(msg);})
        .take(10)
        .blocking_subscribe([](std::string msg){
            std::cout << msg << std::endl;
        });

    return 0;
}
```

**Comment by thorstink** [comment]
Oh! These look like some very helpful approaches for me to study. As you might be obvious from my code, I am new to rx in general so these examples help me a lot (and hopefully some other people too) to progress beyond the examples. 

I will try them out tomorrow and learn a bit - and I will close this if I do not have questions/remarks. Thanks for your time (and nice library)!

**Comment by thorstink** [comment]
Ok; so I tried some stuff and progressed a little bit. I also encountered something not going right as the CPU goes 100% using your two examples while the initial/my example does not. I can not really put my finger on it. Only thing I changed is replacing  `.blocking_subscribe` with `.as_blocking()
.subscribe(...)` because otherwise it throws a compile error:
```
error: no member named 'blocking_subscribe' in 'rxcpp::observable<std::__1::basic_string<char>, rxcpp::operators::detail::take<std::__1::basic_string<char>, rxcpp::observable<std::__1::basic_string<char>, rxcpp::operators::detail::lift_operator<std::__1::basic_string<char>, rxcpp::operators::detail::lift_operator<std::__1::basic_string<char>, rxcpp::operators::detail::merge<rxcpp::observable<std::__1::basic_string<char>, rxcpp::dynamic_observable<std::__1::basic_string<char> > >, rxcpp::observable<rxcpp::observable<std::__1::basic_string<char>, rxcpp::dynamic_observable<std::__1::basic_string<char> > >, rxcpp::dynamic_observable<rxcpp::observable<std::__1::basic_string<char>, rxcpp::dynamic_observable<std::__1::basic_string<char> > > > >, rxcpp::identity_one_worker>, rxcpp::operators::detail::observe_on<std::__1::basic_string<char>, rxcpp::observe_on_one_worker> >, rxcpp::operators::detail::map<std::__1::basic_string<char>, (lambda at /Users/Thomas/workspace/src/ReactiveRobotics/example/src/main.cc:50:14)> > >, int> >`
``` 
I am not sure if that `.as_blocking().subscribe(...)` is the same as `.blocking_subscribe(...)` (and if it can cause the 100% CPU-issue). 

As for my previous message; the following seems to work for me (and I can use it this way with the existing interfaces I have for some drivers). However, this implementation (similar to your first suggestion) races to 100%-cpu. None the less, the code:

```cpp

template<class Obs>
class sensordriver {
public:
    sensordriver(Obs o, std::string msg, int t) : o_(o), msg_(msg), t_(t) {}
    void listen() {
        for (;;) {
            if (!o_.is_subscribed()) { return;}
            o_.on_next(msg_); // msg_ actually changes over time.. 
            if (!o_.is_subscribed()) { return;}
            std::this_thread::sleep_for(std::chrono::seconds(t_));  // simulating time in between receiving stuff
        }
    }
    Obs o_;
    std::string msg_;
    int t_;
};

template<typename T>
sensordriver<T> CreateDriver(const T & obs, std::string msg, int t)
{
    return sensordriver<T>(obs, msg, t);
}

auto driver(int t, std::string msg) {
  return rxcpp::sources::create<std::string>([t, msg](auto out){
    std::thread th([t, msg, out](){
        auto a = CreateDriver(out, msg, t);
        a.listen();
    });
    th.detach();
    return out.get_subscription();
  });
}
```
Do you have any idea on what could cause CPU-load? I toyed around with some prints but I have no idea!

**Comment by kirkshoop** [comment]
yes, it should have been as_blocking().subscribe() not blocking_subscribe() 

I think that the CPU load is due to #430. This needs to be fixed and I think I understand the fix.

the interval solutions are for situations when you want to sample a sensor at a fixed rate. keeping a thread for each sensor is pretty expensive, is there some other way to get signaled when the sensor is ready to read?

**Comment by thorstink** [comment]
Some (simple) sensors / IO stuff that come over the same bus are handled in two threads. Some other (more complex) sensors, connected to a different (hardware) busses is different. The vendor-supplied API for these devices quite often uses a blocking call waiting for a new measurement (and sometimes access to a buffer). It depends on device. 

I can and will test any solution you figure out (although probably not much better than you can do yourself).

**Comment by ajmalk** [comment]
One question that hasn't been answered here is difference between subjects and behaviors. As far as I can tell, the only thing the behavior adds is a convenience function to the latest value.

**Comment by kirkshoop** [comment]
subject does not have a value because it does not store a value. 

replay subject will store 0 or more values and new subscribers are sent the stored and then are connected to any new values. replay does not take an initial set of values at construction this is why the only way to access values is to subscribe.

behavior subject will store 1 value and new subscribers are sent the stored value and then are connected to any new values. behavior requires the initial value at construction and provides access to that value, but never guarantees that the value it returns is the latest value updates potentially race with value requests. subscriptions to behavior are always guaranteed to have the latest value.

**Comment by kirkshoop** [comment]
@thorstink, I made a change that I believe will help with the cpu usage, please try it and let me know how it goes!

**Comment by thorstink** [comment]
I tested it and verified with htop on ubuntu 16.04: '0% CPU' (compared to the 100% which it was before). Later today I will also verify on macos.

Thanks for all the effort you put into rxcpp! I am enjoying it a lot so far, really gives a new twist to cpp-programming.

**Comment by kirkshoop** [comment]
Thank you for the report. Come back if you have more questions!
