### ISSUE TITLE
travis CI failures [stack.nl is not accessible]

### ISSUE THREAD

**Issue by iam** [ReactiveX/RxCpp#482]
`[](https://travis-ci.org) ** continuous-integration/travis-ci/pr**` target appears to fail

Here's an example:
https://travis-ci.org/ReactiveX/RxCpp/jobs/491863729

```
The command "wget --quiet -O - http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz" failed 3 times.
```

Visiting ftp.stack.nl, we get a DNS name resolution failure. Their site states that maybe they aren't offering these public services anymore?

https://www.stack.nl/notice.html

Should we upload `doxygen-1.8.11.linux.bin.tar.gz` somewhere else (perhaps github itself) and fix the scripts?

**Comment by kirkshoop** [comment]
Thanks for this. I merged a different fix for this issue.
