### ISSUE TITLE
new_thread scheduler thread safety

### ISSUE THREAD

**Issue by lebdron** [ReactiveX/RxCpp#492]
Thread sanitizer detects a data race in the following code:
```C++
rxcpp::composite_subscription lifetime;
auto worker =
    rxcpp::observe_on_new_thread().create_coordinator(lifetime).get_worker();
std::vector<std::thread> threads;
for (int i = 0; i < 20; ++i) {
  threads.emplace_back([&worker] {
    worker.schedule([&worker](const auto &) {
      for (size_t i = 0; i < 4294967292l / 6; ++i)
        ;
      printf("Work\n");
    });
  });
}
for (auto &t : threads) {
  t.join();
}
lifetime.unsubscribe();
```
https://gist.github.com/lebdron/883aa78504bc8b9b564e744e2951fb52

Should this bool be made atomic, or there is some other issue with the scheduler?
https://github.com/ReactiveX/RxCpp/blob/ce5dfc2fdd49693cd109a5f5470b73e982c33f35/Rx/v2/src/rxcpp/rx-scheduler.hpp#L97

**Comment by kirkshoop** [comment]
Yes, I agree with TSAN. The isallowed bool should be accessed atomically.
