### ISSUE TITLE
Pass Array to Onnext

### ISSUE THREAD

**Issue by Zifkan** [ReactiveX/RxCpp#507]
i have definition something like this:

`rxcpp::subjects::subject<ray_hit[]> RayHitSubject = rxcpp::subjects::subject<ray_hit[]>();`

and in implementation:

` ray_hit rayhit[2];
 RayHitSubject.get_subscriber().on_next(rayhit);
`
and im getting error:
`Error	C2664	'void rxcpp::observer<T,rxcpp::subjects::detail::multicast_observer<T>,void,void,void>::on_next(T (&&)) const': cannot convert argument 1 from 'ray_hit *' to 'T (&)'	
`
Im not familiar in c++ so how should i pass rayhit array as argument?

**Comment by kirkshoop** [comment]
in C++ you would either use `std::vector<ray_hit>` for dynamic arrays or `std::array<2, ray_hit>` for fixed-size arrays.
