### ISSUE TITLE
How to use operators on a list of Observables

### ISSUE THREAD

**Issue by Saied-Za** [ReactiveX/RxCpp#520]
hello, i'm a little new to cpp and rxCpp community, i was wondering if i could perform operators on a dynamic number of observables. it seems that these operators only accept Variadic arguments, which i couldn't work dynamically with.
to elaborate my problem with an example, how to merge a std::list of observables?
Thanks in advance.

**Comment by kirkshoop** [comment]
Hi!

take a look at the examples for [`iterate`](http://reactivex.io/RxCpp/rx-iterate_8hpp.html) 

for example, this would iterate over a container of observables.

```
    std::array< rxcpp::observable<int>, 3 > a={{rxcpp::just(1), rxcpp::just(2), rxcpp::just(3)}};
    auto values = rxcpp::observable<>::iterate(a);
    values.
        merge().
        subscribe(
            [](int v){printf("OnNext: %d\n", v);},
            [](){printf("OnCompleted\n");});
```
