### ISSUE TITLE
Maintenance update

### ISSUE THREAD

**Issue by ericoporto** [ReactiveX/RxCpp#552]
Sorry for asking, but is this library still maintained? I see it hasn't had activity for a bit of time. Is there a roadmap for it? I really want to use it - I already use Rx with TypeScript and having on Cpp would be useful.

**Comment by robbeykaaso** [comment]
here is a mini framework for quickly buiding your maintanable application. It only provide the codes of c++ based on QT and qml. I guess you can use the similar concepts to write the same framework by your own developing language.

**Comment by xgao1023** [comment]
Exactly the same question from me.
At least in case if there is some bugs/features and I were able to create some PR, is it going to be reviewed and integrated?

**Comment by antekone** [comment]
I don't think it's maintained. Documentation contains dead links, examples from documentation are not compileable.

**Comment by xgao1023** [comment]
> Exactly the same question from me.
> At least in case if there is some bugs/features and I were able to create some PR, is it going to be reviewed and integrated?

I think I'm going to use it anyway, it mostly working fine. And in case something need to be fixed I probably going to fork it and fix myself.

**Comment by geiseri** [comment]
I was wondering if most of this could be replaced by ranges and coroutines but I am not sure.  The hard part is that RX handles flow control where ranges are more of a lazy on-demand.  That being said, when it works rxcpp is quite nice.  It's just a bit of a bear to figure it out. :(

**Comment by kirkshoop** [comment]
I have some help maintaining rxcpp now and some time myself to contribute. I made a new release and I am updating the CI
