### ISSUE TITLE
combine_latest thread safe

### ISSUE THREAD

**Issue by finch-yihe** [ReactiveX/RxCpp#554]
![Screenshot from 2021-07-08 16-04-35](https://user-images.githubusercontent.com/23740883/124885835-3fd0b480-e006-11eb-83c8-9967a50d5e27.png)
when I try to run this code, it turns out that the member is_set of the class rxcpp::util::detail::maybe is false and std::terminal() was called, like this:
![Screenshot from 2021-07-08 15-07-06](https://user-images.githubusercontent.com/23740883/124878109-5246f000-dffe-11eb-9088-e6e6522e68e6.png)
anyone can help me?

**Comment by finch-yihe** [comment]
`#include <iostream>
#include "rxcpp/rx.hpp"
#include <thread>
#include <unistd.h>

using test = std::shared_ptr<int>;

void fun(rxcpp::subjects::behavior<test> subject, int us, int init){
	int init_ = init;
	while(true){
		init_ += 2;
		subject.get_subscriber().on_next(std::make_shared<int>(init_));
		usleep(us * 100);
	}
}

int main()
{
	rxcpp::subjects::behavior<test> a(std::make_shared<int>(1));
	rxcpp::subjects::behavior<test> b(std::make_shared<int>(2));
	
	auto c = rxcpp::synchronize_new_thread();
	a.get_observable().observe_on(c)
	 .combine_latest(b.get_observable().observe_on(c))
	 .subscribe([](std::tuple<test, test> tuple){
		 auto one = std::get<0>(tuple);
		 auto two = std::get<0>(tuple);
		 std::cout << "thread:" << std::this_thread::get_id() << " [" << *one << "," << *two << "]" << std::endl;
	 });
	
	std::thread a_(&fun, a, 1, 0);
	std::thread b_(&fun, b, 2, 1);
	a_.join();
	b_.join();
	return 0;
}`

**Comment by finch-yihe** [comment]
how can i promise thread safety about using combine_latest with two different observable in two different thread

**Comment by nikobarli** [comment]
Try to pass "coordination" to combine_latest, e.g.

`o1.combine_latest(rxcpp::observe_on_new_thread(), o2)`

For operators receiving it's input from two or more observables injected by multiple threads, you should put coordination to handle the synchronization.

**Comment by finch-yihe** [comment]
> Try to pass "coordination" to combine_latest, e.g.
> 
> `o1.combine_latest(rxcpp::observe_on_new_thread(), o2)`
> 
> For operators receiving it's input from two or more observables injected by multiple threads, you should put coordination to handle the synchronization.

thank u
